version: '3'

services:
  gateway:
    build: ./Gateway
    ports:
      - '3000:3000'

  service_discovery:
    build: ./Service
    ports:
      - '3002:3002'

  order_service:
    build: ./Order
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - '5000:5000'

  payment_service:
    build: ./Payment
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - '5001:5001'